# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20170620_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerprofile',
            name='user',
        ),
    ]
