language: python
python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c "create database test_imager_db;" -U postgres

# command to install dependencies
install:
  - pip install -r requirements.pip
  - pip install coveralls

# command to run tests
script:
  - python imagersite/manage.py migrate
  - coverage run imagersite/manage.py test imagersite
#coverage run imagersite/manage.py test imagersite

after_success:
  - coveralls

# # safelist
# branches:
#   only:
#   - models-1
#   - front-end-1

notifications:
  email: false
