# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='published',
            field=models.CharField(choices=[('PR', 'Private'), ('SH', 'Shared'), ('PU', 'Public')], default='PV', max_length=2),
        ),
    ]
