# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 17:09
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20170707_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='photos'),
        ),
    ]
