# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 21:54
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0006_auto_20170718_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='tags',
        ),
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
